# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58ae9e07bf2724516c2bbf8d4277a81944bec144f1731f9d04763582abb82248c13c0942bb4a447f1352c889442d29c6f68d31a3ce171281e80e8a6454a0244

test:
  secret_key_base: a801058ee6d96903db95cf2cfa6d3299fdda03ad489858c6f105d642d6bc29547c242d2e84aecc41824de230f292036a9283afaf4c3ee24f6a9db2721cbfeb21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
